const propertiesData = [
  {
    name: "Beautiful House 1",
    location: "123 Main Street, City A",
    bedrooms: 3,
    bathrooms: 2,
    rent: 1500,
    area: "1200 sqft",
    image: "/Images/1.png",
    date: "2023-08-10",
    houseType: "Independent House",
    propertyType: "Residential",
  },
  {
    name: "Beautiful House 2",
    location: "456 Park Avenue, City B",
    bedrooms: 4,
    bathrooms: 3,
    rent: 2200,
    area: "1800 sqft",
    image: "/Images/2.png",
    date: "2023-08-15",
    houseType: "Villa",
    propertyType: "Residential",
  },
  {
    name: "Luxurious Apartment",
    location: "789 Oak Street, City C",
    bedrooms: 2,
    bathrooms: 2,
    rent: 3000,
    area: "1000 sqft",
    image: "/Images/3.png",
    date: "2023-08-20",
    houseType: "Apartment",
    propertyType: "Residential",
  },
  {
    name: "Spacious House",
    location: "321 Elm Road, City D",
    bedrooms: 4,
    bathrooms: 3,
    rent: 2500,
    area: "2000 sqft",
    image: "/Images/4.png",
    date: "2023-08-12",
    houseType: "Independent House",
    propertyType: "Commercial", // Example of a different property type
  },
  {
    name: "Elegant Villa",
    location: "654 Maple Lane, City E",
    bedrooms: 5,
    bathrooms: 4,
    rent: 3500,
    area: "2500 sqft",
    image: "/Images/5.png",
    date: "2023-08-18",
    houseType: "Villa",
    propertyType: "Residential",
  },
  {
    name: "Modern Apartment 2",
    location: "789 Cedar Street, City F",
    bedrooms: 2,
    bathrooms: 2,
    rent: 2000,
    area: "1100 sqft",
    image: "/Images/6.png",
    date: "2023-09-01",
    houseType: "Apartment",
    propertyType: "Residential",
  },
  {
    name: "Charming Cottage",
    location: "321 Pine Avenue, City G",
    bedrooms: 1,
    bathrooms: 1,
    rent: 1200,
    area: "800 sqft",
    image: "/Images/7.png",
    date: "2023-09-05",
    houseType: "Cottage",
    propertyType: "Residential",
  },
  {
    name: "Spacious Condo",
    location: "654 Willow Lane, City H",
    bedrooms: 3,
    bathrooms: 2,
    rent: 2600,
    area: "1500 sqft",
    image: "/Images/8.png",
    date: "2023-09-08",
    houseType: "Condo",
    propertyType: "Residential",
  },
  {
    name: "Luxury Penthouse",
    location: "987 Oakwood Road, City I",
    bedrooms: 4,
    bathrooms: 4,
    rent: 4500,
    area: "3000 sqft",
    image: "/Images/9.png",
    date: "2023-09-12",
    houseType: "Penthouse",
    propertyType: "Residential",
  },
  {
    name: "Commercial Office",
    location: "345 Elm Street, City J",
    bedrooms: 0,
    bathrooms: 1,
    rent: 1800,
    area: "1200 sqft",
    image: "/Images/10.png",
    date: "2023-09-18",
    houseType: "Office Space",
    propertyType: "Commercial",
  },
  {
    name: "Cozy Cabin",
    location: "765 Birch Avenue, City K",
    bedrooms: 2,
    bathrooms: 1,
    rent: 1400,
    area: "900 sqft",
    image: "/Images/1.png",
    date: "2023-09-20",
    houseType: "Cabin",
    propertyType: "Residential",
  },
  {
    name: "Industrial Warehouse",
    location: "543 Maple Road, City L",
    bedrooms: 0,
    bathrooms: 0,
    rent: 3500,
    area: "5000 sqft",
    image: "/Images/2.png",
    date: "2023-09-22",
    houseType: "Warehouse",
    propertyType: "Commercial",
  },
  {
    name: "Seaside Villa",
    location: "987 Oceanview Drive, City M",
    bedrooms: 6,
    bathrooms: 5,
    rent: 6000,
    area: "4000 sqft",
    image: "/Images/3.png",
    date: "2023-09-25",
    houseType: "Villa",
    propertyType: "Residential",
  },
  {
    name: "Modern Townhouse",
    location: "876 Sunset Boulevard, City N",
    bedrooms: 3,
    bathrooms: 3,
    rent: 2800,
    area: "1600 sqft",
    image: "/Images/4.png",
    date: "2023-09-28",
    houseType: "Townhouse",
    propertyType: "Residential",
  },
];

export default propertiesData;
